language: node_js

node_js:
  - 8
  - 6

cache:
  directories:
    - ~/.npm

notifications:
  email:
    recipients:
      - arizzitano@edx.org
      - jbradley@edx.org
    on_success: always
    on_failure: always

script:
  - npm run lint
  - npm run test

after_script:
  - npm run coveralls
  - npm run semantic-release
