name: Node.js CI

on:
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VER }}
    - name: Install dependencies
      run: npm ci
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo $GITHUB_HEAD_REF)" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Preview semantic-release version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
      run: |
        echo "$GITHUB_HEAD_REF"
        echo "${{ steps.extract_branch.outputs.branch}}"
        git checkout $GITHUB_HEAD_REF
        unset GITHUB_ACTIONS
        unset GITHUB_EVENT_NAME
        npx semantic-release --dry-run --no-ci --branches=${{ steps.extract_branch.outputs.branch }}
