name: Release CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - alpha
    - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: Build
      run: npm run build
    - name: Build Docs
      run: npm run build-docs
    - name: Coverage
      uses: codecov/codecov-action@v3
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.OPENEDX_SEMANTIC_RELEASE_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.OPENEDX_SEMANTIC_RELEASE_NPM_TOKEN }}
      run: npx semantic-release
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: www/public # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
